# Generated by Django 4.2 on 2025-09-13 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.CharField(help_text='Domeniu sau IP', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=10, null=True)),
                ('ports', models.JSONField(default=dict)),
                ('tls', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('email_auth', models.JSONField(default=dict)),
                ('cves', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.target')),
            ],
        ),
    ]
