# Generated by Django 4.2 on 2025-09-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='subdomains',
            field=models.JSONField(default=list),
        ),
    ]
