# Generated by Django 4.2 on 2025-09-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scan_subdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='subdomain_scans',
            field=models.JSONField(default=list),
        ),
    ]
